
;MARK:TextureOverrideVB
; dffb91a3
[TextureOverride_VB_dffb91a3_dffb91a3_Position]
cs-t1 = Resourcedffb91a3Blend
cs-t0 = Resourcedffb91a3Position
match_cs = 93db774c5ca9a3ea
match_cs_t0_hash = dbc98878
match_cs_t1_hash = bfa79855
handling = skip
dispatch = 246,1,1

[TextureOverride_VB_dffb91a3_dffb91a3_Texcoord]
hash = 726d6e75
vb1 = Resourcedffb91a3Texcoord

[TextureOverride_VB_dffb91a3_dffb91a3_Blend]
hash = 28f8dae3


;MARK:TextureOverrideIB
[TextureOverride_IB_dffb91a3]
hash = dffb91a3
handling = skip

[TextureOverride_LOD0.dffb91a3_0]
hash = dffb91a3
match_first_index = 0
ib = Resource_LOD0.dffb91a3_0_Index
; [mesh:LOD0.dffb91a3-0] [vertex_count:15715]
drawindexed = 60159,0,0


;MARK:ResourceBuffer
[Resourcedffb91a3Position]
type = Buffer
stride = 40
filename = Meshes/dffb91a3-Position.buf

[Resourcedffb91a3Texcoord]
type = Buffer
stride = 24
filename = Meshes/dffb91a3-Texcoord.buf

[Resourcedffb91a3Blend]
type = Buffer
stride = 32
filename = Meshes/dffb91a3-Blend.buf

[Resource_LOD0.dffb91a3_0_Index]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Meshes/LOD0.dffb91a3-0-Index.buf


;sha256=c89719c7008158372ca1b61e62524811498dc5c8be863e5e2b0b595e61a42dff

